export const ENGLISH_WEBVIEW_MESSAGES = {
  history: 'Chat history',
  newConversation: 'New conversation',
  extensionSettings: 'Extension settings',
  plugins: 'Plugins',
  pluginCenter: 'DSH Plugins',
  closePluginCenter: 'Close plugin center',
  pluginMarketplace: 'Marketplace',
  installedPlugins: 'Installed',
  searchPlugins: 'Search plugins…',
  allCategories: 'All categories',
  refreshPlugins: 'Refresh plugin catalog',
  curatedPlugins: 'Curated list',
  browsePluginTopic: 'GitHub topic',
  pluginCatalogSummary: 'Showing {visible} of {total} loaded · {marketTotal} on GitHub',
  noMatchingPlugins: 'No matching plugins.',
  noInstalledPlugins: 'No profile plugins installed yet.',
  loadMorePlugins: 'Load more',
  installCustomPlugin: 'Install a package',
  customPluginPlaceholder: 'npm package, github:owner/repo, local path, or tarball URL',
  pluginSecurityNotice: 'Third-party plugins run outside the Agent sandbox. Review their source before installing.',
  nativeUiCompatibilityNotice: 'Host tools and policies work here. UI marked “Official Web UI” targets the upstream browser client and may not appear in this native workbench.',
  pluginWorking: 'Applying plugin changes and restarting Harness…',
  viewSource: 'Source',
  install: 'Install',
  installed: 'Installed',
  remove: 'Remove',
  officialWebUi: 'Official Web UI',
  githubTopicSource: 'GitHub Topic',
  curatedSource: 'Curated',
  builtinSource: 'Built-in',
  pluginSuite: 'Suite',
  agentCompatible: 'Agent compatible',
  partialCompatibility: 'Agent works · Web UI unavailable',
  unknownCompatibility: 'Compatibility unknown',
  webUiOnly: 'Official Web UI only',
  backToParentAgent: 'Back to parent agent',
  renameConversation: 'Rename conversation',
  forkConversation: 'Fork from the current progress',
  archiveSession: 'Archive conversation',
  restoreSession: 'Restore conversation',
  archivedConversations: 'Archived',
  archivedSearchHint: '{count} archived conversations match. Open Archived to continue them.',
  exportSession: 'Export session (ZIP)',
  importSession: 'Import sessions',
  compact: 'Compact',
  sessionSettings: 'Session settings',
  configurationTitle: 'Model and DSH mode',
  configurationSource: 'DeepSeek source',
  configurationSwitchSource: 'Switch DeepSeek source',
  configurationModels: 'Models',
  configurationModes: 'DSH modes',
  configurationEffort: 'Effort',
  configurationClose: 'Close model and mode settings',
  configurationOpen: 'Choose DeepSeek source, model, DSH mode, and reasoning effort',
  configurationAppliesNextMessage: 'Changes apply when you send the next message.',
  modeStartsNewConversation: 'Changing DSH mode starts a new conversation when you send.',
  configurationSummary: '{model} · {mode} · Effort {effort}',
  contextUsageSummary: 'Context {used} / {limit} · {percent}% used',
  model: 'Model',
  reasoning: 'Reasoning',
  agent: 'Agent',
  apiKeyRequired: 'Configure an API Key in Connection settings first.',
  configure: 'Configure',
  connectionSettings: 'Connection settings',
  baseUrl: 'Base URL',
  provider: 'Provider',
  providerDeepseekOfficial: 'DeepSeek Official',
  providerName: 'Name',
  providerNamePlaceholder: 'Provider name',
  addProvider: 'Add provider…',
  confirmRemove: 'Confirm removal',
  apiKey: 'API Key',
  apiKeyPlaceholder: 'Enter a new API Key',
  apiKeyKeepPlaceholder: 'Configured — leave blank to keep it',
  providerModels: 'Model IDs',
  providerModelsPlaceholder: 'deepseek-v4-flash, deepseek-v4-pro',
  providerModelsHint: 'Model ids your endpoint exposes, comma-separated. Use an id that supports the features you need (e.g. agent plan).',
  openNativeSettings: 'Open full settings',
  apply: 'Apply',
  closeSettings: 'Close settings',
  settingsHint: 'Changes are stored by Harness and apply to the next request without a restart.',
  testConnection: 'Test connection',
  testingConnection: 'Testing…',
  connectionModelsFound: 'Connection successful. Found {count} models.',
  connectionTestUnsupported: 'Connection testing is not available for this provider.',
  connectionUnreachable: 'Connection failed.',
  baseUrlInvalid: 'Enter a valid Base URL.',
  baseUrlInvalidScheme: 'Base URL must use http:// or https://.',
  searchConversations: 'Search conversations…',
  startingHarness: 'Starting Harness',
  startingHarnessDescription: 'The extension is starting its bundled runtime. No separate deployment is required.',
  connectionFailed: 'Connection failed',
  retry: 'Retry',
  logs: 'Logs',
  loadOlder: 'Load older messages',
  emptyTitle: 'What can I help you build?',
  emptyDescription: 'Read code, edit files, run commands, make plans, or delegate complex work to Harness agents.',
  plan: 'Plan',
  timeline: 'Timeline',
  skills: 'Skills',
  jobs: 'Jobs',
  agents: 'Agents',
  slashCommands: 'Slash commands',
  promptPlaceholder: 'Ask DeepSeek Harness… Type / for commands, @ for files',
  message: 'Message',
  attachSelection: 'Attach the active editor selection to the message',
  selection: 'Selection',
  attachedContext: 'Attached editor context',
  imageAttachment: 'Image attachment',
  imageAttachments: 'Image attachments',
  removeImageAttachment: 'Remove image attachment',
  imagePreview: 'Image preview',
  closeImagePreview: 'Close image preview',
  workspaceFiles: 'Workspace files',
  openSelectedFile: 'Open the selected code in the editor',
  selectionContextMeta: '{language} · L{start}–{end}',
  removeSelectionContext: 'Remove selected code context',
  openReferencedFile: 'Open referenced file',
  removeFileContext: 'Remove file context',
  searchingWorkspaceFiles: 'Searching workspace files…',
  noMatchingFiles: 'No matching workspace files.',
  context: 'Context',
  contextDescription: 'Plans, Skills, and background jobs',
  permissionDescription: 'Harness file and command permissions',
  permissionLabel: 'Permissions',
  permissionFullAccessTitle: 'Enable full access?',
  permissionFullAccessWarning: 'Full access lets the agent edit any file and run any command without asking first. Only enable it for tasks you trust.',
  permissionFullAccessConfirm: 'Yes, enable full access',
  send: 'Send',
  sendTitle: 'Send (Enter)',
  stopGenerating: 'Stop generating',
  activityWorking: 'Working…',
  activityEscHint: 'esc to interrupt',
  composerHint: 'Enter to send · Shift+Enter for a new line · @ to attach files · paste images',
  connected: 'Connected',
  reconnecting: 'Reconnecting',
  connectionError: 'Error',
  starting: 'Starting',
  unknownError: 'Unknown error',
  noMatchingConversations: 'No matching conversations',
  noArchivedConversations: 'No archived conversations',
  status: 'Status',
  you: 'You',
  reasoningProcess: 'Think',
  thinking: 'Thinking…',
  thinkingWithTokens: 'Thinking… · {tokens} tokens',
  thoughtFor: 'Thought for {duration}',
  thoughtForWithTokens: 'Thought for {duration} · {tokens} tokens',
  workedFor: 'Worked for {duration}',
  tool: 'Tool',
  toolArguments: 'Arguments',
  toolResult: 'Tool result',
  toolTokens: '· {tokens} tokens',
  approvalRequired: 'Approval required: {tool}',
  reject: 'Reject',
  allowOnce: 'Allow once',
  questionRequired: 'Harness needs your input',
  otherAnswer: 'Other answer (optional)',
  submitAnswer: 'Submit answer',
  planChanging: 'Changing Plan mode',
  planEnabled: 'Plan mode enabled',
  planDisabled: 'Plan mode disabled',
  enable: 'Enable',
  disable: 'Disable',
  createGoal: 'Create persistent goal',
  goalPhaseActive: 'active',
  goalPhasePaused: 'paused',
  goalPhaseBlocked: 'blocked',
  goalPhaseComplete: 'complete',
  goalRounds: '{phase} · {current}/{max} rounds',
  pause: 'Pause',
  resume: 'Resume',
  markComplete: 'Mark complete',
  clear: 'Clear',
  continuableConversation: 'Continuable',
  oneShot: 'One-shot',
  hasChildAgents: ' · has child agents',
  noContent: 'Nothing here yet',
  oneShotReadOnly: 'One-shot sub-agent · read-only',
  runningQueue: 'Running · Enter to queue',
  queuedPromptPlaceholder: 'Add a follow-up… (queued)',
  queuedMessages: 'Queued',
  sessionChanges: 'Session changes',
  changesChanged: 'Changed',
  changesFiles: 'files',
  changesKeepAll: 'Keep All',
  sendNow: 'Send now',
  removeQueued: 'Withdraw',
  editQueued: 'Edit',
  save: 'Save',
  cancel: 'Cancel',
  continuableSubagent: 'Continuable sub-agent',
  justNow: 'Just now',
  minutesAgo: '{count} min ago',
  hoursAgo: '{count} hr ago',
  code: 'Code',
  copy: 'Copy',
  copied: 'Copied',
  copyConclusion: 'Copy conclusion',
  copyCode: 'Copy {language} code',
} as const

export type WebviewMessageKey = keyof typeof ENGLISH_WEBVIEW_MESSAGES
export type WebviewMessages = Record<WebviewMessageKey, string>
export type MessageArguments = Record<string, string | number>

export interface WebviewLocalizationBootstrap {
  readonly language: string
  readonly messages: WebviewMessages
}

declare global {
  // Set by the nonce-protected bootstrap script before the Webview bundle.
  var __DEEPSEEK_HARNESS_LOCALIZATION__: WebviewLocalizationBootstrap | undefined
}

export function localizeWebviewMessages(localize: (message: string) => string): WebviewMessages {
  return Object.fromEntries(
    Object.entries(ENGLISH_WEBVIEW_MESSAGES).map(([key, message]) => [key, localize(message)]),
  ) as WebviewMessages
}

export function createWebviewTranslator(
  bootstrap = globalThis.__DEEPSEEK_HARNESS_LOCALIZATION__,
): (key: WebviewMessageKey, args?: MessageArguments) => string {
  const messages = bootstrap?.messages ?? ENGLISH_WEBVIEW_MESSAGES
  return (key, args = {}) => formatMessage(messages[key] ?? ENGLISH_WEBVIEW_MESSAGES[key], args)
}

function formatMessage(message: string, args: MessageArguments): string {
  return message.replace(/\{([a-zA-Z][a-zA-Z0-9]*)\}/gu, (placeholder, key: string) => {
    const value = args[key]
    return value === undefined ? placeholder : String(value)
  })
}
