import { describe, expect, it } from 'vitest'
import type { HistoryEntry } from '../src/gateway/gateway-wire.js'
import { projectConversation, type ChatItem } from '../src/domain/workbench-state.js'
import { projectContextSource, runtimeContextItems, visibleTranscript } from '../src/domain/transcript-context.js'
import { projectProcessingStatus } from '../src/domain/processing-status.js'

function injected(seq: number, source: object, text: string, surfaceOp = 'append'): HistoryEntry {
  return { event: { seq, time: seq + 1, type: 'user/message', surfaceOp,
    data: { id: `u${seq}`, role: 'user', source, content: [{ type: 'text', text }] },
  } } as unknown as HistoryEntry
}
const snapshot = { kind: 'plugin', plugin: '@deepseek-ai/dsh-system-prompt', form: 'snapshot', sections: [] }
const modelSource = { kind: 'plugin', plugin: 'model-selection', form: 'notice', summary: 'deepseek-v4-flash → glm-5.3-flash' }
const modelText = '[model changed: assistant turns above this point were generated by deepseek-v4-flash; the session continues with glm-5.3-flash]'

describe('runtime context presentation', () => {
  it('keeps V3 system messages and replacements in the inspector, never the transcript', () => {
    const system = (seq: number, text: string, replacement = false): HistoryEntry => ({ event: {
      type: 'system/message', seq, time: seq + 1,
      surfaceOp: replacement ? { op: 'replace', startSeq: 0, endSeq: 0 } : 'append',
      data: { turn: 1, step: 1, message: { id: `system-${seq}`, role: 'system', source: { kind: 'plugin', plugin: 'custom-persona' }, content: [{ type: 'text', text }] } },
    } } as unknown as HistoryEntry)
    const entries = [system(0, 'First prompt'), injected(1, { kind: 'user' }, 'Hello'), system(2, 'Updated prompt', true)]
    const before = JSON.stringify(entries)
    const items = projectConversation(entries).messages
    expect(visibleTranscript(items).map((item) => item.id)).toEqual(['event-1'])
    expect(runtimeContextItems(items).map((item) => item.blocks?.[0]?.text)).toEqual(['First prompt', 'Updated prompt'])
    expect(JSON.stringify(entries)).toBe(before)
  })

  it('hides initialization material, retaining the raw log and inspectable originals', () => {
    const entries = [injected(0, { kind: 'user' }, 'hello'),
      injected(1, snapshot, 'Current runtime context. Sandbox policy'),
      injected(2, { kind: 'skill-catalog', form: 'catalog' }, '<system-reminder>skills</system-reminder>'),
      injected(3, { kind: 'workspace-files', form: 'instructions' }, 'Workspace guidance')]
    const before = JSON.stringify(entries)
    const projected = projectConversation(entries).messages
    expect(visibleTranscript(projected).map((item) => item.id)).toEqual(['event-0'])
    expect(runtimeContextItems(projected).map((item) => item.id)).toEqual(['event-1', 'event-2', 'event-3'])
    expect(projected[1]?.contextSource).toEqual({ kind: 'plugin', plugin: snapshot.plugin, form: 'snapshot' })
    expect(projected[1]?.blocks?.[0]?.text).toContain('Sandbox policy')
    expect(JSON.stringify(entries)).toBe(before)
    expect(projected).toHaveLength(4)
  })

  it('keeps a brand-new context-only session visually empty', () => {
    const items = projectConversation([injected(0, snapshot, 'Runtime'), injected(1, { kind: 'skill-catalog' }, 'Skills')]).messages
    expect(visibleTranscript(items)).toEqual([])
    expect(runtimeContextItems(items)).toHaveLength(2)
    expect(visibleTranscript([])).toEqual([])
  })

  it('projects a compact model notice while retaining its original only for inspection', () => {
    const items = projectConversation([injected(5, modelSource, modelText)]).messages
    const [notice] = visibleTranscript(items)
    expect(notice).toEqual({ id: 'event-5', seq: 5, time: 6, kind: 'notice', status: 'info', contextNotice: { kind: 'model-change', model: 'glm-5.3-flash' } })
    expect(notice?.blocks).toBeUndefined()
    expect(runtimeContextItems(items)[0]?.blocks?.[0]?.text).toBe(modelText)
  })

  it('uses the historical target, never the active model or a truncated summary', () => {
    const longModel = 'provider/' + 'long-model-id-'.repeat(20)
    const items = projectConversation([
      injected(0, { ...modelSource, summary: 'old → long…' }, modelText.replace('glm-5.3-flash', longModel)),
      injected(1, modelSource, 'Future producer format'),
      injected(2, { ...modelSource, summary: 'old → truncated…' }, 'Future producer format'),
    ]).messages
    expect(visibleTranscript(items).map((item) => item.contextNotice)).toEqual([
      { kind: 'model-change', model: longModel }, { kind: 'model-change', model: 'glm-5.3-flash' }, { kind: 'model-change' },
    ])
  })

  it('never classifies human text, assistant text or opaque plugins by matching prompt words', () => {
    const items = projectConversation([
      injected(0, { kind: 'user' }, modelText), injected(1, { kind: 'plugin', plugin: 'opaque-plugin' }, modelText),
    ]).messages
    const assistant: ChatItem = { id: 'answer', seq: 2, time: 3, kind: 'message', role: 'assistant', blocks: [{ kind: 'text', text: 'Current runtime context' }] }
    const all = [...items, assistant]
    expect(visibleTranscript(all)).toEqual(all)
    expect(visibleTranscript(all)[0]).toBe(items[0])
  })

  it('preserves relay/recall/unknown messages and shows declared notice summaries', () => {
    const items = projectConversation([
      injected(0, { kind: 'plugin', plugin: 'agent', form: 'relay' }, 'Please review this task'),
      injected(1, { kind: 'plugin', plugin: 'recall', form: 'recall' }, 'Previous result'),
      injected(2, { kind: 'plugin', plugin: 'future', form: 'future-form' }, 'Future content'),
      injected(3, { kind: 'plugin', plugin: 'permissions', form: 'notice', summary: 'Read-only enabled' }, 'Long model-facing policy reminder'),
    ]).messages
    expect(visibleTranscript(items).slice(0, 3)).toEqual(items.slice(0, 3))
    expect(visibleTranscript(items)[3]?.contextNotice).toEqual({ kind: 'summary', text: 'Read-only enabled' })
  })

  it('supports older runtime provenance without form, and tolerates missing metadata', () => {
    const items = projectConversation([
      injected(0, { kind: 'plugin', plugin: snapshot.plugin }, 'Runtime'),
      injected(1, { kind: 'skill-catalog' }, 'Skills'),
    ]).messages
    const legacy: ChatItem = { id: 'old', seq: 2, time: 3, kind: 'context', title: 'Unknown', blocks: [] }
    expect(visibleTranscript([...items, legacy])).toEqual([legacy])
    expect(projectContextSource({ kind: 'plugin', form: 42, plugin: null, summary: {} } as unknown as { kind: string })).toEqual({ kind: 'plugin' })
  })

  it('preserves errors and waiting indicators when internal snapshots are appended', () => {
    const internal = projectConversation([injected(2, snapshot, 'runtime')]).messages
    const error: ChatItem = { id: 'error', seq: 1, time: 2, kind: 'notice', status: 'error', detail: 'Connection failed' }
    const messages = visibleTranscript([error, ...internal])
    const active = { running: true, approvals: [], questions: [] }
    expect(messages).toEqual([error])
    expect(projectProcessingStatus(active, messages, 'connected')).toEqual({ kind: 'hidden' })
    expect(projectProcessingStatus(active, visibleTranscript(internal), 'connected')).toEqual({ kind: 'working' })
    expect(projectProcessingStatus({ ...active, approvals: [{ key: 'approval', toolName: 'bash' }] }, [], 'connected')).toEqual({ kind: 'hidden' })
  })
})
