import type { HarnessConfiguration } from '../config/configuration.js'

/** Generates a trusted overlay from validated VS Code settings. */
export function renderOverlay(configuration: HarnessConfiguration): string {
  const thinking = configuration.reasoningEffort === 'off' ? 'disabled' : 'enabled'
  return `# Generated by DeepSeek Harness for VS Code. Manual edits are overwritten.
- id: llm-deepseek
  config:
    thinking: ${thinking}
    reasoningEffort: ${configuration.reasoningEffort}

- id: agent-default-model
  config:
    provider: ${JSON.stringify(configuration.provider)}
    model: ${configuration.model}

- id: agent-presets
  config:
    default: ${configuration.agentPreset}

- id: permission
  config:
    # Patch rows replace their complete config, so restate every shipped preset.
    presets:
      read-only:
        sandbox: read-only
        approval: ask
        name: Read only
        description: Prevent file writes while keeping approval prompts enabled.
      workspace-write:
        sandbox: workspace-write
        approval: ask
        name: Workspace write
        description: Allow workspace and temporary-directory writes with approval for wider access.
      danger-full-access:
        sandbox: danger-full-access
        approval: never
        name: Full access
        description: Allow unrestricted file writes without approval prompts.
    defaultPreset: ${configuration.permissionMode}
`
}
