import { pathToFileURL } from 'node:url'
import { join } from 'node:path'
import type { HarnessConfiguration } from '../config/configuration.js'

/** Generates a trusted overlay from validated VS Code settings. */
export function renderOverlay(configuration: HarnessConfiguration, gatewayPluginPath: string, historyHome?: string, compression: 'zstd' | 'none' = 'zstd'): string {
  const webSearchRow = configuration.webSearch ? '' : `- id: web-search-deepseek
  disabled: true

`
  const historyRows = historyHome === undefined ? '' : `
- id: session-persistence-jsonl
  config:
    root: ${JSON.stringify(join(historyHome, 'sessions'))}
    compression: ${compression}

- id: attachment-local
  config:
    dshHome: ${JSON.stringify(historyHome)}

`
  return `# Generated by DeepSeek Harness for VS Code. Manual edits are overwritten.
${historyRows}
- id: web-runtime
  # This bundle row mounts dsh-host-frontend-static, so disable it completely.
  disabled: true

# The native VS Code workbench does not mount the official Web document
# preview. Keep DSH's file APIs available, but do not start its Office-to-PDF
# host service or require the platform LibreOffice engine in the VSIX.
- id: office-to-pdf
  disabled: true
- id: ui-sidebar-documentpreview
  disabled: true

- insert:
    # Keep the official API transport alive by providing only the bind facts
    # consumed by dsh-client-connection. No HTTP fallback is registered.
    - id: vscode-gateway-runtime
      name: ${JSON.stringify(pathToFileURL(gatewayPluginPath).href)}
      config:
        printUrl: true

${webSearchRow}- id: llm-deepseek
  config:
    reasoningEffort: ${configuration.reasoningEffort}

- id: session-log-deepseek
  config:
    enabled: false

- id: plugin-package-inventory-deepseek
  config:
    enabled: false

- id: agent-default-model
  config:
    provider: ${JSON.stringify(configuration.provider)}
    model: ${JSON.stringify(configuration.model)}

- id: agent-preset-registry
  config:
    default: ${configuration.agentPreset}

- id: permission
  config:
    # Patch rows replace their complete config, so restate every shipped preset.
    presets:
      read-only:
        sandbox: read-only
        approval: ask
        name: Read only
        description: Prevent file writes while keeping approval prompts enabled.
      workspace-write:
        sandbox: workspace-write
        approval: ask
        name: Workspace write
        description: Allow workspace and temporary-directory writes with approval for wider access.
      danger-full-access:
        sandbox: danger-full-access
        approval: never
        name: Full access
        description: Allow unrestricted file writes without approval prompts.
    defaultPreset: ${configuration.permissionMode}
`
}
