import type { ChatItem } from './workbench-state.js'

/** Only presentation metadata crosses the bridge; catalog/section bodies stay in blocks. */
export interface ContextSourceView {
  readonly kind: string
  readonly plugin?: string
  readonly form?: string
  readonly summary?: string
}

export type ContextNoticeView =
  | { readonly kind: 'model-change'; readonly model?: string }
  | { readonly kind: 'summary'; readonly text: string }

/** Keep provenance instead of trying to classify arbitrary message text in the UI. */
export function projectContextSource(source: { readonly kind: string }): ContextSourceView {
  const metadata = source as { readonly plugin?: unknown; readonly form?: unknown; readonly summary?: unknown }
  return {
    kind: source.kind,
    ...(typeof metadata.plugin === 'string' ? { plugin: metadata.plugin } : {}),
    ...(typeof metadata.form === 'string' ? { form: metadata.form } : {}),
    ...(typeof metadata.summary === 'string' ? { summary: metadata.summary } : {}),
  }
}

/**
 * The normal transcript is a view, never a rewrite of the model's log. Internal
 * instructions/catalogs/snapshots live in the inspector. Relays, recalls and
 * unknown plugin messages remain visible so task output cannot silently vanish.
 */
export function visibleTranscript(messages: readonly ChatItem[]): readonly ChatItem[] {
  return messages.flatMap((item): ChatItem[] => {
    if (item.kind !== 'context') return [item]
    const source = item.contextSource
    if (source?.kind === 'plugin' && source.plugin === 'model-selection') {
      const model = modelSwitchTarget(item)
      return [asNotice(item, { kind: 'model-change', ...(model === undefined ? {} : { model }) })]
    }
    if (source?.form === 'notice' && source.summary?.trim()) {
      return [asNotice(item, { kind: 'summary', text: source.summary.trim() })]
    }
    if (source?.kind === 'skill-catalog'
      || (source?.kind === 'plugin' && source.plugin === '@deepseek-ai/dsh-system-prompt')
      || source?.form === 'instructions' || source?.form === 'catalog' || source?.form === 'snapshot') return []
    return [item]
  })
}

/** Full originals, including model notices, remain explicitly inspectable. */
export function runtimeContextItems(messages: readonly ChatItem[]): readonly ChatItem[] {
  return messages.filter((item) => item.kind === 'context')
}

function asNotice(item: ChatItem, contextNotice: ContextNoticeView): ChatItem {
  return { id: item.id, seq: item.seq, time: item.time, kind: 'notice', status: 'info', contextNotice }
}

function modelSwitchTarget(item: ChatItem): string | undefined {
  // The producer's summary is capped at 120 characters. Its exact, versioned
  // notice body retains long model ids. Parse only after checking provenance;
  // a human quoting this sentence must never be reclassified or hidden.
  const text = item.blocks?.filter((block) => block.kind === 'text').map((block) => block.text).join('\n') ?? ''
  const full = /^\[model changed: assistant turns above this point were generated by [^\r\n]+; the session continues with ([^\r\n]+)\]$/.exec(text.trim())?.[1]?.trim()
  if (full) return full
  const target = item.contextSource?.summary?.split(' → ').at(1)?.trim()
  return target && !/(?:…|\.\.\.)$/.test(target) ? target : undefined
}
